Fix websocket handler signature for websockets v12+
Removed 'path' parameter from websocket_handler() to match the
new websockets v12+ API. The path parameter was deprecated and
removed in newer versions of the websockets library.

This fixes the TypeError: 'missing 1 required positional argument: path'